name: Build and Release

on:
  push:
    tags:
      - 'v*' # 推送以v开头的标签时触发，如v1.0.0

jobs:
  build-exe:
    name: Build EXE
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed your_script.py
        # 如果有其他资源文件需要包含，添加 --add-data 参数
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-exe
        path: dist/
        
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies for Kivy
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3-dev ffmpeg \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          
    - name: Install Kivy and Buildozer
      run: |
        pip install --upgrade pip setuptools virtualenv
        pip install kivy buildozer cython==0.29.19
        
    - name: Initialize Buildozer
      run: |
        buildozer init
        # 根据需要修改生成的 buildozer.spec 文件
        
    - name: Build APK
      run: |
        buildozer -v android debug
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: bin/
        
  create-release:
    name: Create Release
    needs: [build-exe, build-apk]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: |
          Automated release for ${{ github.ref }}
          - EXE application for Windows
          - APK application for Android
        draft: false
        prerelease: false
        files: |
          artifacts/windows-exe/your_script.exe
          artifacts/android-apk/your_app-0.1-debug.apk
