name: Multi-Arch Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-exe-64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Python 64-bit
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        architecture: x64

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build 64-bit EXE
      run: pyinstaller --onefile ok_school_life.py

    - uses: actions/upload-artifact@v4
      with:
        name: exe-64
        path: dist/

  build-exe-32:
    # 保持之前的 32 位构建步骤不变...

  create-release:
    needs: [build-exe-64, build-exe-32]
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        artifacts: |
          artifacts/exe-64/*.exe
          artifacts/exe-32/*.exe
        token: ${{ secrets.GITHUB_TOKEN }}
