name: Multi-Arch Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-exe-32:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
    - uses: actions/checkout@v4

    - name: Configure Wine
      run: |
        # 添加 32 位支持
        sudo dpkg --add-architecture i386

        # 安装基础依赖
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          gnupg \
          ca-certificates

        # 配置 WineHQ 仓库
        wget -qO- https://dl.winehq.org/wine-builds/winehq.key | \
          gpg --dearmor | \
          sudo tee /usr/share/keyrings/winehq-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/winehq-archive-keyring.gpg] https://dl.winehq.org/wine-builds/debian/ bookworm main" | \
          sudo tee /etc/apt/sources.list.d/winehq.list
        sudo apt-get update

        # 安装 Wine
        sudo apt-get install -y \
          --install-recommends \
          winehq-stable

    - name: Build 32-bit EXE
      run: |
        # 此处添加具体构建命令
        wine python -m Py
