name: Multi-Arch Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-exe-64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Python 64-bit
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        architecture: x64

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build 64-bit EXE
      run: pyinstaller --onefile ok_school_life.py

    - uses: actions/upload-artifact@v4
      with:
        name: exe-64
        path: dist/

  build-exe-32:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
    - uses: actions/checkout@v4

    - name: Install 32-bit Dependencies
      run: |
        dpkg --add-architecture i386
        apt-get update
        apt-get install -y wine-stable python3-pip gcc-multilib

    - name: Download 32-bit Python
      run: |
        wget https://www.python.org/ftp/python/3.10.0/python-3.10.0-embed-win32.zip
        unzip python-3.10.0-embed-win32.zip -d py32

    - name: Install PyInstaller for 32-bit
      run: wine py32/python.exe -m pip install pyinstaller

    - name: Build 32-bit EXE
      run: wine py32/python.exe -m PyInstaller --onefile ok_school_life.py

    - uses: actions/upload-artifact@v4
      with:
        name: exe-32
        path: dist/

  create-release:
    needs: [build-exe-64, build-exe-32]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        artifacts: |
          artifacts/exe-64/*.exe
          artifacts/exe-32/*.exe
        token: ${{ secrets.GITHUB_TOKEN }}