name: Multi-Arch Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-exe-32:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
    - uses: actions/checkout@v4

    - name: Configure isolated environment
      run: |
        # 创建隔离环境
        export WORKSPACE="/tmp/build_$(date +%s)"
        export WINEPREFIX="$WORKSPACE/wine32"
        export WINEARCH=win32
        export HOME="$WORKSPACE/home"
        export XDG_RUNTIME_DIR="$WORKSPACE/runtime"
        
        mkdir -p "$WORKSPACE"
        chmod -R 700 "$WORKSPACE"
        echo "WORKSPACE=$WORKSPACE" >> $GITHUB_ENV

    - name: Initialize Wine
      env:
        WINEPREFIX: ${{ env.WORKSPACE }}/wine32
        WINEARCH: win32
      run: |
        # 初始化wine配置
        xvfb-run -a wine wineboot --init
        # 写入注册表永久配置
        wine reg add "HKEY_CURRENT_USER\\Environment" /v WINEPREFIX /t REG_SZ /d "$WINEPREFIX" /f
        # 验证配置
        wine reg query "HKEY_CURRENT_USER\\Environment" /v WINEPREFIX

    # ...后续步骤保持WINEPREFIX环境变量一致...
